import { useMemo, useState } from "react";
import { ABILITY_REGISTRY } from "../../config/abilityRegistry";
import { GIFT_ABILITY_MAP } from "../../config/giftAbilityMap";
import { abilityEventQueue } from "../../core/abilityEventQueue";
import { configManager } from "../../core/configManager";
import { audioManager } from "../../core/audioManager";
import { AVAILABLE_SOUNDS } from "../../config/soundCatalog";

const FREEZE_GIFTS=[{id:"twinkling_star",name:"Twinkling Star"}];
const DEFAULT_FREEZE={duration:300,scope:"TEAM",activationGift:"Twinkling Star",activationGiftId:"twinkling_star",sound:"/Sounds/5-4-3-2-1-are-you-ready.mp3",rescueCount:2};
const inputStyle={background:"#100d18",color:"#fff",border:"1px solid rgba(255,255,255,.14)",borderRadius:"7px",padding:"7px 9px",fontSize:"11px",width:"100%",boxSizing:"border-box"};
const selectStyle={...inputStyle,cursor:"pointer"};
const buttonStyle={background:"rgba(255,255,255,.07)",color:"#fff",border:"1px solid rgba(255,255,255,.14)",borderRadius:"7px",padding:"6px 9px",fontSize:"10px",fontWeight:800,cursor:"pointer"};
const labelStyle={display:"block",color:"#8f9bb3",fontSize:"9px",fontWeight:800,textTransform:"uppercase",letterSpacing:".06em",marginBottom:"5px"};
const sectionStyle={background:"rgba(12,10,20,.72)",border:"1px solid rgba(255,255,255,.09)",borderRadius:"12px",padding:"14px"};
const normalizeSound=s=>{if(!s)return"";if(typeof s==="string")return s;if(typeof s==="object")return s.path||s.url||s.src||s.file||s.value||s.name||"";return String(s);};
const soundLabel=s=>{const v=normalizeSound(s);return v?(v.split(/[\\/]/).pop()||v):"— Sin sonido —";};
function loadAbilities(){const saved=configManager.get("abilities")||{};return Object.fromEntries(Object.entries(ABILITY_REGISTRY).map(([id,base])=>{const current=saved[id]||{};return[id,{...base,...current,display:{...base.display,...current.display},gameAction:{...base.gameAction,...current.gameAction},scoreAction:{...base.scoreAction,...current.scoreAction},sound:normalizeSound(current.sound??base.sound)||null,animation:current.animation??base.animation??""}];}));}
function loadGiftMap(){const saved=configManager.get("abilityGiftMap");return Array.isArray(saved)?saved.map(x=>({...x})):GIFT_ABILITY_MAP.map(x=>({...x}));}
function loadFreeze(){const saved=configManager.get("battleEffects.freeze")||{};return{...DEFAULT_FREEZE,...saved,sound:normalizeSound(saved.sound??DEFAULT_FREEZE.sound)};}
export function AbilityManagerControls(){
 const [abilities,setAbilities]=useState(loadAbilities);const[abilityGiftMap,setAbilityGiftMap]=useState(loadGiftMap);const[freezeConfig,setFreezeConfig]=useState(loadFreeze);
 const soundOptions=useMemo(()=>[...new Set([...Object.values(abilities).map(a=>normalizeSound(a.sound)).filter(Boolean),normalizeSound(freezeConfig.sound),...(AVAILABLE_SOUNDS||[]).map(normalizeSound).filter(Boolean)])],[abilities,freezeConfig.sound]);
 const saveAbility=(id,patch)=>{const latest=configManager.get("abilities")||{};const current=latest[id]||abilities[id]||ABILITY_REGISTRY[id];const next={...current,...patch,sound:patch.sound!==undefined?(normalizeSound(patch.sound)||null):(normalizeSound(current.sound)||null),animation:patch.animation!==undefined?String(patch.animation||""):String(current.animation||""),display:patch.display?{...(current.display||{}),...patch.display}:current.display,gameAction:patch.gameAction?{...(current.gameAction||{}),...patch.gameAction}:current.gameAction,scoreAction:patch.scoreAction?{...(current.scoreAction||{}),...patch.scoreAction}:current.scoreAction};configManager.set(`abilities.${id}`,next);setAbilities(prev=>({...prev,[id]:{...prev[id],...next}}));};
 const saveMapping=(abilityId,field,value)=>{const next=abilityGiftMap.map(item=>item.abilityId===abilityId?{...item,[field]:value}:item);setAbilityGiftMap(next);configManager.set("abilityGiftMap",next);};
 const saveFreeze=patch=>{const next={...DEFAULT_FREEZE,...(configManager.get("battleEffects.freeze")||{}),...patch};setFreezeConfig(next);configManager.set("battleEffects.freeze",next);};
 const preview=s=>{const sound=normalizeSound(s);if(sound)audioManager.previewSound(sound);};
 const runPreview=ability=>{const mapping=abilityGiftMap.find(x=>x.abilityId===ability.abilityId);abilityEventQueue.enqueue({abilityId:ability.abilityId,sourceGift:mapping?.giftName||"Gift",teamId:"team1",sender:"ADMIN_PREVIEW",source:"ADMIN_PREVIEW",display:ability.display,gameAction:ability.gameAction,scoreAction:ability.scoreAction,duration:ability.duration||10000,sound:normalizeSound(ability.sound),animation:ability.animation||""});preview(ability.sound);};
 return <div style={{background:"rgba(18,14,28,.96)",border:"1px solid rgba(255,255,255,.12)",borderRadius:"14px",padding:"16px",display:"flex",flexDirection:"column",gap:"16px"}}>
   <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:"12px",flexWrap:"wrap",paddingBottom:"13px",borderBottom:"1px solid rgba(255,255,255,.09)"}}><div><div style={{color:"#00f5ff",fontSize:"16px",fontWeight:950}}>⚡ ABILITY MANAGER</div><div style={{color:"#77839a",fontSize:"10px",marginTop:"3px"}}>Un solo lugar para asignar regalo + sonido + animación + acción.</div></div><span style={{background:"rgba(0,245,255,.08)",border:"1px solid rgba(0,245,255,.18)",color:"#8cefff",borderRadius:"999px",padding:"5px 9px",fontSize:"10px",fontWeight:900}}>{Object.keys(abilities).length} ABILITIES</span></div>
   <section style={sectionStyle}><div style={{color:"#fff",fontSize:"13px",fontWeight:900,marginBottom:"10px"}}>⚡ ABILITIES / REGALOS</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(310px,1fr))",gap:"10px"}}>{Object.values(abilities).map(ability=>{const mapping=abilityGiftMap.find(x=>x.abilityId===ability.abilityId)||{giftName:"",giftId:"",aliases:[]};return <article key={ability.abilityId} style={{background:"linear-gradient(145deg,rgba(255,255,255,.045),rgba(255,255,255,.015))",border:"1px solid rgba(0,245,255,.16)",borderLeft:"3px solid #00f5ff",borderRadius:"10px",padding:"12px"}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"10px"}}><div style={{display:"flex",gap:"8px",alignItems:"center"}}><div style={{width:"36px",height:"36px",display:"grid",placeItems:"center",borderRadius:"9px",background:"rgba(0,245,255,.1)",fontSize:"19px"}}>{ability.display?.icon||"⚡"}</div><div><input value={ability.display?.name||""} onChange={e=>saveAbility(ability.abilityId,{display:{...ability.display,name:e.target.value}})} style={{...inputStyle,fontSize:"13px",fontWeight:900,border:"none",background:"transparent",padding:0}}/><div style={{color:"#68758b",fontSize:"9px",fontFamily:"monospace"}}>{ability.abilityId}</div></div></div><span style={{color:ability.enabled===false?"#f56565":"#48bb78",fontSize:"9px",fontWeight:900}}>{ability.enabled===false?"● DISABLED":"● ACTIVE"}</span></div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"8px"}}><div><label style={labelStyle}>🎁 Gift Name</label><input value={mapping.giftName||""} placeholder="Ej. Ice Cream Cone" onChange={e=>saveMapping(ability.abilityId,"giftName",e.target.value)} style={inputStyle}/></div><div><label style={labelStyle}>TikTok Gift ID</label><input value={mapping.giftId||""} placeholder="Ej. 12345" onChange={e=>saveMapping(ability.abilityId,"giftId",e.target.value)} style={inputStyle}/></div><div><label style={labelStyle}>Aliases</label><input value={(mapping.aliases||[]).join(", ")} onChange={e=>saveMapping(ability.abilityId,"aliases",e.target.value.split(",").map(v=>v.trim()).filter(Boolean))} style={inputStyle}/></div><div><label style={labelStyle}>🎬 Animation ID</label><input value={ability.animation||""} placeholder="Ej. cocazo / freeze / galaxy" onChange={e=>saveAbility(ability.abilityId,{animation:e.target.value})} style={inputStyle}/></div><div><label style={labelStyle}>🎵 Sound</label><select value={normalizeSound(ability.sound)} onChange={e=>saveAbility(ability.abilityId,{sound:e.target.value||null})} style={selectStyle}><option value="">— Sin sonido —</option>{soundOptions.map(s=><option key={s} value={s}>{soundLabel(s)}</option>)}</select></div><div><label style={labelStyle}>Action</label><input value={ability.gameAction?.value||""} onChange={e=>saveAbility(ability.abilityId,{gameAction:{...(ability.gameAction||{}),value:e.target.value}})} style={inputStyle}/></div><div><label style={labelStyle}>Duration ms</label><input type="number" min="1000" value={ability.duration||10000} onChange={e=>saveAbility(ability.abilityId,{duration:Math.max(1000,Number(e.target.value)||10000)})} style={inputStyle}/></div><div><label style={labelStyle}>Score</label><input type="number" value={ability.scoreAction?.value??0} onChange={e=>saveAbility(ability.abilityId,{scoreAction:{...(ability.scoreAction||{}),value:Number(e.target.value)||0}})} style={inputStyle}/></div></div>
      <div style={{display:"flex",gap:"6px",marginTop:"9px",flexWrap:"wrap"}}><button onClick={()=>preview(ability.sound)} style={buttonStyle}>🔊 Test Sound</button><button onClick={()=>runPreview(ability)} style={{...buttonStyle,color:"#00f5ff"}}>▶ Test Ability</button><button onClick={()=>saveAbility(ability.abilityId,{enabled:ability.enabled===false})} style={{...buttonStyle,color:ability.enabled===false?"#48bb78":"#f6ad55"}}>{ability.enabled===false?"Enable":"Disable"}</button></div>
    </article>})}</div></section>
   <section style={{...sectionStyle,background:"linear-gradient(145deg,rgba(0,140,220,.10),rgba(0,70,110,.04))",border:"1px solid rgba(0,245,255,.18)"}}><div style={{color:"#00f5ff",fontSize:"13px",fontWeight:950,marginBottom:"10px"}}>❄️ FREEZE</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:"9px"}}><div><label style={labelStyle}>🎁 Activator</label><select value={freezeConfig.activationGiftId} onChange={e=>{const g=FREEZE_GIFTS.find(x=>x.id===e.target.value);if(g)saveFreeze({activationGiftId:g.id,activationGift:g.name});}} style={selectStyle}>{FREEZE_GIFTS.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></div><div><label style={labelStyle}>🔊 Sound</label><select value={normalizeSound(freezeConfig.sound)} onChange={e=>saveFreeze({sound:e.target.value})} style={selectStyle}><option value="">— Sin sonido —</option>{soundOptions.map(s=><option key={s} value={s}>{soundLabel(s)}</option>)}</select></div><div><label style={labelStyle}>Duration</label><input type="number" min="5" value={freezeConfig.duration} onChange={e=>saveFreeze({duration:Math.max(5,Number(e.target.value)||300)})} style={inputStyle}/></div><div><label style={labelStyle}>Scope</label><select value={freezeConfig.scope} onChange={e=>saveFreeze({scope:e.target.value})} style={selectStyle}><option value="TEAM">TEAM</option><option value="GLOBAL">GLOBAL</option></select></div></div><div style={{marginTop:"9px"}}><button onClick={()=>preview(freezeConfig.sound)} style={{...buttonStyle,color:"#00f5ff"}}>🔊 Test Freeze Sound</button></div></section>
   <div style={{fontSize:"9px",color:"#69758a",textAlign:"center",padding:"4px"}}>Gift Sound Overrides fue eliminado. Los sonidos se asignan directamente dentro de cada Ability y permanecen guardados.</div>
 </div>;
}
