import { eventBus } from "./eventBus";
import { registrationManager } from "./registrationManager";
import { recordMvpContribution } from "./mvpLeaderboardManager";

const STORAGE_KEY = "cocoloco_round_contributions_v1";
let state = { roundId:null, winLimpia:null, gift:null, contributions:[] };
function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch(e){}}
function playerSnapshot(playerId){if(!playerId)return null;const p=registrationManager.getRegisteredPlayers().find(x=>String(x.playerId)===String(playerId));return p?{playerId:p.playerId,name:p.displayName||p.username,username:p.username,teamId:p.teamId,avatar:p.avatar||""}:null;}
function normalizePlayer(payload={}){const id=payload.playerId||payload.id||payload.tiktokId||payload.username;if(!id)return null;return{playerId:id,name:payload.name||payload.displayName||payload.username||String(id),username:payload.username||payload.name||String(id),teamId:payload.teamId||null,avatar:payload.avatar||""};}
export function beginRoundContributionTracking(roundId){state={roundId,winLimpia:null,gift:null,contributions:[]};persist();}
export function recordWinLimpia(payload={}){const player=normalizePlayer(payload)||playerSnapshot(payload.playerId);if(!player)return null;state.winLimpia={...player,points:1,timestamp:Date.now()};state.contributions.push({type:"WIN_LIMPIA",...player,points:1,timestamp:Date.now()});recordMvpContribution({player,source:"WIN_LIMPIA",points:1,roundId:state.roundId});persist();eventBus.publish("mvp:contribution_pending",{type:"WIN_LIMPIA",player,roundId:state.roundId});return state.winLimpia;}
export function recordGift(payload={}){const senderId=payload.playerId||payload.tiktokId||payload.id||payload.username;const player=normalizePlayer(payload)||playerSnapshot(senderId);if(!player)return null;state.gift={...player,giftName:payload.giftName||payload.sourceGift||payload.canonicalGiftId||"Gift",abilityId:payload.abilityId||null,timestamp:Date.now()};state.contributions.push({type:"GIFT",...state.gift,timestamp:Date.now()});persist();eventBus.publish("mvp:gift_contribution",{roundId:state.roundId,contribution:state.gift});return state.gift;}
export function selectWinLimpiaRecipient(playerId){const player=playerSnapshot(playerId);if(!player)return{success:false,reason:"PLAYER_NOT_FOUND"};state.winLimpia={...player,points:1,selectedManually:true,timestamp:Date.now()};state.contributions.push({type:"WIN_LIMPIA",...state.winLimpia});recordMvpContribution({player:state.winLimpia,source:"WIN_LIMPIA",points:1,roundId:state.roundId});persist();eventBus.publish("mvp:recipient_selected",{type:"WIN_LIMPIA",player:state.winLimpia,roundId:state.roundId});return{success:true,player:state.winLimpia};}
export function selectGiftRecipient(playerId,giftName="Gift"){const player=playerSnapshot(playerId);if(!player)return{success:false,reason:"PLAYER_NOT_FOUND"};state.gift={...player,giftName,selectedManually:true,timestamp:Date.now()};state.contributions.push({type:"GIFT",...state.gift});recordMvpContribution({player:state.gift,source:"GIFT",points:1,roundId:state.roundId});persist();eventBus.publish("mvp:recipient_selected",{type:"GIFT",player:state.gift,roundId:state.roundId});return{success:true,player:state.gift};}
export function getRoundContributions(){return JSON.parse(JSON.stringify(state));}
export function clearRoundContributions(){state={roundId:null,winLimpia:null,gift:null,contributions:[]};persist();}
if(typeof window!=="undefined"){try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)state={...state,...JSON.parse(saved)};}catch(e){}eventBus.subscribe("win:correct",recordWinLimpia);eventBus.subscribe("ability:started",recordGift);}
