import { useState, useEffect, useRef } from "react";
import { getPlayerMvpRounds, getPlayerContributionPoints } from "../../core/mvpLeaderboardManager";
import { eventBus } from "../../core/eventBus";

export function TeamPanel({ team, score, players, round, wrapperClass, isFrozen, roundMvpTitle, frozenDetails, isDamaged, isGalaxyBenefited, galaxyPopup, isDonutActive, isCowboyActive }) {
  if (!team) return null;
  const topPlayers=(players||[]).filter(p=>p.teamId===team.id).sort((a,b)=>{if((b.points||0)!==(a.points||0))return(b.points||0)-(a.points||0);if((b.wins||0)!==(a.wins||0))return(b.wins||0)-(a.wins||0);return(b.messages||0)-(a.messages||0);}).slice(0,10);
  const winMvpId=round?.contributions?.winLimpia?.playerId||null;
  const giftMvpId=round?.contributions?.gift?.playerId||null;
  const [rankDeltas,setRankDeltas]=useState({});
  const [mvpRefresh,setMvpRefresh]=useState(0);
  const prevRanksRef=useRef({});
  const [showCommand,setShowCommand]=useState(false);
  const commandPrompt=Array.isArray(team.commands)&&team.commands.length>0?String(team.commands[0]).trim():"";
  const teamMode=String(team.mode||team.gameMode||team.gameModeId||team.variant||team.type||team.category||team.teamMode||"").toUpperCase();
  const teamGender=String(team.gender||team.genderType||team.genderRole||team.sex||"").toLowerCase();
  const teamLabel=String(team.name||"").toLowerCase();
  const isGenderBattle=teamMode.includes("GENDER")||teamMode.includes("CHICOS")||teamMode.includes("CHICAS")||teamGender.length>0||/\b(chico|chicos|chica|chicas|hombre|hombres|mujer|mujeres|masculino|femenino)\b/.test(teamLabel);
  const isGirlsTeam=isGenderBattle&&(teamGender.includes("female")||teamGender.includes("woman")||teamGender.includes("mujer")||teamGender.includes("femen")||/\b(chica|chicas|mujer|mujeres|femenino|femenina)\b/.test(teamLabel));
  const isBoysTeam=isGenderBattle&&!isGirlsTeam&&(teamGender.includes("male")||teamGender.includes("man")||teamGender.includes("hombre")||teamGender.includes("mascul")||/\b(chico|chicos|hombre|hombres|masculino|masculina)\b/.test(teamLabel));
  const genderTheme=isGirlsTeam?{background:"linear-gradient(135deg,#f64f9b 0%,#ff86bf 34%,#ffd35a 68%,#8edcff 100%)",border:"rgba(255,82,169,.96)",glow:"rgba(255,92,176,.58)",accent:"#8b174f",pattern:"rgba(255,255,255,.16)"}:isBoysTeam?{background:"linear-gradient(135deg,#145bb8 0%,#239fe5 34%,#6dd8ef 58%,#6b9d58 82%,#3d6639 100%)",border:"rgba(91,211,255,.96)",glow:"rgba(39,163,255,.62)",accent:"#07365e",pattern:"rgba(255,255,255,.13)"}:null;
  useEffect(()=>{const unsubs=["mvp:recipient_selected","mvp:contribution_pending","mvp:gift_contribution","round:finished"].map(name=>eventBus.subscribe(name,()=>setMvpRefresh(v=>v+1)));return()=>unsubs.forEach(u=>u?.());},[]);
  useEffect(()=>{const newRanks={},deltas={};topPlayers.forEach((player,index)=>{const currentRank=index+1,prevRank=prevRanksRef.current[player.id];if(prevRank!==undefined&&prevRank>currentRank){const delta=prevRank-currentRank;deltas[player.id]=delta;setTimeout(()=>setRankDeltas(prev=>{const copy={...prev};delete copy[player.id];return copy;}),2200);}newRanks[player.id]=currentRank;});prevRanksRef.current=newRanks;if(Object.keys(deltas).length>0)setRankDeltas(prev=>({...prev,...deltas}));},[topPlayers,mvpRefresh]);
  useEffect(()=>{if(!commandPrompt||isFrozen||isDamaged||isGalaxyBenefited||isDonutActive||isCowboyActive){setShowCommand(false);return undefined;}const intervalId=setInterval(()=>setShowCommand(prev=>!prev),4000);return()=>clearInterval(intervalId);},[commandPrompt,isFrozen,isDamaged,isGalaxyBenefited,isDonutActive,isCowboyActive]);
  const showCommandPrompt=!!commandPrompt&&showCommand&&!isFrozen&&!isDamaged&&!isGalaxyBenefited&&!isDonutActive&&!isCowboyActive;
  const commandStyle={color:"#050505",background:"rgba(255,255,255,.96)",border:genderTheme?`1px solid ${genderTheme.border}`:"1px solid rgba(0,0,0,.38)",borderRadius:"999px",padding:"2px 6px",boxShadow:"0 1px 3px rgba(0,0,0,.28)",textShadow:"none",filter:"none",animation:"commandPromptClean 1.8s ease-in-out infinite"};
  const genderDecor=genderTheme?{position:"absolute",inset:0,pointerEvents:"none",zIndex:1,overflow:"hidden",borderRadius:"6px",backgroundImage:`repeating-linear-gradient(135deg,transparent 0px,transparent 12px,${genderTheme.pattern} 13px,transparent 15px),radial-gradient(circle at 12% 24%,${genderTheme.pattern} 0 2px,transparent 3px),radial-gradient(circle at 82% 72%,${genderTheme.pattern} 0 2px,transparent 3px)`,backgroundSize:"auto,auto,auto",animation:"genderPatternDrift 8s linear infinite"}:null;
  const genderSymbol=isGirlsTeam?"✦ ♥ ✦":"▲ ◆ ⚑";
  return <div className={`team-wrapper ${wrapperClass} ${isGenderBattle?"gender-team-wrapper":""} ${isGirlsTeam?"gender-girls":""} ${isBoysTeam?"gender-boys":""}`} style={{position:"relative"}}>
    <div className={`team-card ${isFrozen?"punished":""} ${isDamaged?"damaged":""} ${isDonutActive?"donut-active":""} ${isCowboyActive?"cowboy-active":""} ${isGalaxyBenefited?"galaxy-active":""}`} style={genderTheme&&!isFrozen&&!isDamaged&&!isGalaxyBenefited&&!isDonutActive&&!isCowboyActive?{background:genderTheme.background,border:`1.5px solid ${genderTheme.border}`,boxShadow:`0 0 16px ${genderTheme.glow},inset 0 0 18px rgba(255,255,255,.12)`,animation:"genderCardFloat 4.2s ease-in-out infinite"}:{}}>
      {genderDecor&&<><div style={genderDecor}/><div style={{position:"absolute",left:"7px",bottom:"3px",zIndex:2,pointerEvents:"none",fontSize:"7px",letterSpacing:"3px",fontWeight:900,color:"rgba(255,255,255,.24)",textShadow:"0 1px 2px rgba(0,0,0,.35)",animation:"genderSymbolPulse 4s ease-in-out infinite"}}>{genderSymbol}</div><div style={{position:"absolute",right:"7px",top:"3px",zIndex:2,pointerEvents:"none",fontSize:"6px",letterSpacing:"2px",fontWeight:900,color:"rgba(255,255,255,.22)",transform:"rotate(-8deg)",animation:"genderSymbolPulse 4.8s ease-in-out infinite reverse"}}>{genderSymbol}</div></>}
      {isDamaged&&<div className="ability-layer ability-layer-money" style={{position:"absolute",inset:0,pointerEvents:"none",zIndex:3,overflow:"hidden"}}><div style={{position:"absolute",inset:0,background:"radial-gradient(circle at 15% 25%,rgba(255,0,0,.6) 0%,transparent 35%),radial-gradient(circle at 85% 75%,rgba(255,100,0,.6) 0%,transparent 35%)",opacity:.95}}/><div style={{position:"absolute",top:"5px",left:"10px",fontSize:"11px",transform:"rotate(-12deg)"}}>💥</div><div style={{position:"absolute",top:"10px",right:"18px",fontSize:"10px",transform:"rotate(25deg)"}}>💥</div></div>}
      {isCowboyActive&&<div className="ability-layer ability-layer-cowboy" style={{position:"absolute",inset:0,pointerEvents:"none",zIndex:4,border:"2px solid #ff6622",borderRadius:"6px",boxShadow:"0 0 15px rgba(255,100,34,.8)"}}/>}
      {isDonutActive&&<div className="ability-layer ability-layer-donut" style={{position:"absolute",inset:0,pointerEvents:"none",zIndex:5,border:"2px solid #ff69b4",borderRadius:"6px",boxShadow:"0 0 15px rgba(255,105,180,.8)"}}/>}
      {isGalaxyBenefited&&<div className="ability-layer ability-layer-galaxy" style={{position:"absolute",inset:0,pointerEvents:"none",zIndex:6,border:"2px solid #00ffff",borderRadius:"6px",boxShadow:"0 0 18px rgba(0,245,255,.9)"}}/>}
      {isFrozen&&<div className="ability-layer ability-layer-freeze" style={{position:"absolute",inset:0,backgroundImage:"radial-gradient(white 1.2px,transparent 0),radial-gradient(white 1.8px,transparent 0)",backgroundSize:"14px 14px,22px 22px",backgroundPosition:"0 0,7px 7px",opacity:.7,animation:"snowfall 3.5s linear infinite",pointerEvents:"none",zIndex:7,border:"2px solid #00f0ff",borderRadius:"6px",background:"rgba(0,180,216,.25)"}}/>}
      <div className="team-name" style={{color:isFrozen?"#fff":isDamaged?"#ffb4b4":isGalaxyBenefited?"#fff":isDonutActive?"#fff":isCowboyActive?"#fff":genderTheme?"#fff":undefined,textShadow:isFrozen?"0 0 8px rgba(0,245,255,.9)":isDamaged?"0 0 10px rgba(255,0,0,.9)":isGalaxyBenefited?"0 0 10px rgba(125,211,252,.8)":isDonutActive?"0 0 10px rgba(255,105,180,.8)":isCowboyActive?"0 0 12px rgba(255,100,34,.9)":genderTheme?"0 2px 5px rgba(0,0,0,.55)":"0 2px 5px rgba(0,0,0,.9)",position:"relative",zIndex:8,minHeight:"18px",display:"flex",alignItems:"center",justifyContent:"center"}}>{showCommandPrompt?<span style={{fontSize:"8.5px",fontWeight:950,letterSpacing:".25px",textTransform:"uppercase",whiteSpace:"nowrap",...commandStyle}}>📣 ESCRIBE <strong style={{color:isGirlsTeam?"#a21caf":isBoysTeam?"#075985":"#000",fontWeight:1000}}>{commandPrompt}</strong> PARA UNIRTE</span>:(isFrozen?`❄️ ${team.name} [CONGELADO] ❄️`:isDamaged?`💥 ${team.name} [DESTRUIDO]`:isGalaxyBenefited?`🌌 ${team.name} 🌌`:isDonutActive?`🍩 ${team.name} [EL MUDO]`:isCowboyActive?`🤠 ${team.name} [RETO]`:team.name)}</div>
      <style>{`@keyframes commandPromptClean{0%,100%{opacity:.94;transform:scale(1)}50%{opacity:1;transform:scale(1.018)}}@keyframes genderCardFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-1px)}}@keyframes genderPatternDrift{0%{background-position:0 0,0 0,0 0}50%{background-position:18px 8px,5px -4px,-6px 5px}100%{background-position:36px 16px,0 0,0 0}}@keyframes genderSymbolPulse{0%,100%{opacity:.42;transform:scale(1)}50%{opacity:.78;transform:scale(1.08)}}@keyframes roundsShimmer{0%{background-position:140% 0}55%,100%{background-position:-40% 0}}`}</style>
      <div className={`team-score ${isDonutActive?"clean-number-pop":""}`} style={{color:"#fff",textShadow:isFrozen?"0 0 16px rgba(0,240,255,1)":isDamaged?"0 0 18px rgba(255,0,0,1)":isGalaxyBenefited?"0 0 15px rgba(255,255,255,.7)":isDonutActive?"0 0 15px rgba(255,105,180,.8)":isCowboyActive?"0 0 20px rgba(255,100,34,1)":genderTheme?"0 2px 6px rgba(0,0,0,.6)":"0 2px 8px rgba(0,0,0,.9)",position:"relative",zIndex:8}}>{score}</div>
      <div style={{position:"relative",zIndex:8,width:"100%",display:"flex",justifyContent:"center",alignItems:"center",boxSizing:"border-box"}}>{isFrozen?<div style={{display:"flex",justifyContent:"center",alignItems:"center",width:"100%"}}><div className="freeze-timer-badge"><span style={{fontSize:"11px"}}>❄️ FREEZE:</span><span style={{color:"#fff",fontSize:"12px",marginLeft:"2px"}}>{frozenDetails?.remainingTime||"10"}s</span></div></div>:<div className={`team-rounds-container ${isGalaxyBenefited?"galaxy-rounds-boost":""}`} style={{position:"relative",overflow:"hidden",display:"flex",justifyContent:"center",alignItems:"center",gap:"3px",minHeight:"18px",padding:"2px 7px",borderRadius:"5px",border:isGalaxyBenefited?"1.5px solid #7dd3fc":isDonutActive?"1.5px solid #ff69b4":isCowboyActive?"1.5px solid #ff8a3d":genderTheme?`1.5px solid ${genderTheme.border}`:"1px solid rgba(125,211,252,.55)",background:isGalaxyBenefited?"linear-gradient(135deg,rgba(8,22,38,.98),rgba(24,38,70,.98))":isDonutActive?"linear-gradient(135deg,rgba(38,12,32,.98),rgba(50,18,42,.98))":isCowboyActive?"linear-gradient(135deg,rgba(45,22,10,.98),rgba(60,28,10,.98))":genderTheme?"rgba(0,0,0,.30)":"linear-gradient(135deg,rgba(8,22,38,.98),rgba(22,34,52,.98))",boxShadow:genderTheme?`0 0 9px ${genderTheme.glow},inset 0 1px 2px rgba(255,255,255,.18)`:"0 2px 8px rgba(0,0,0,.65),inset 0 1px 1px rgba(255,255,255,.12),0 0 10px rgba(125,211,252,.16)"}}><div style={{position:"absolute",inset:0,pointerEvents:"none",background:"linear-gradient(105deg,transparent 0%,transparent 42%,rgba(255,255,255,.28) 49%,transparent 56%,transparent 100%)",backgroundSize:"220% 100%",animation:"roundsShimmer 3.2s ease-in-out infinite"}}/><span className="rounds-title" style={{color:"#fff",fontWeight:900,textShadow:"0 1px 4px rgba(0,0,0,.95)",position:"relative",zIndex:2}}>RONDA</span><span className="rounds-digits" style={{color:"#fff",fontWeight:950,textShadow:"0 1px 5px rgba(0,0,0,.95)",position:"relative",zIndex:2}}>{team.wins||0}</span>{isDamaged&&<span style={{fontSize:"5.5px",color:"#ff8f8f",fontWeight:900,whiteSpace:"nowrap",position:"relative",zIndex:2}}>💥 0 PTS</span>}{isGalaxyBenefited&&<span style={{fontSize:"6px",color:"#dbeafe",fontWeight:900,textShadow:"0 0 4px rgba(125,211,252,.9)",whiteSpace:"nowrap",position:"relative",zIndex:2}}>⚡</span>}{isDonutActive&&<span style={{fontSize:"6px",color:"#ffd1ec",fontWeight:900,textShadow:"0 0 4px rgba(255,105,180,.9)",position:"relative",zIndex:2}}>🍩</span>}{isCowboyActive&&<span style={{fontSize:"6px",color:"#ffd0ad",fontWeight:900,textShadow:"0 0 6px rgba(255,153,51,1)",whiteSpace:"nowrap",position:"relative",zIndex:2}}>🤠</span>}</div>}</div>
    </div>
    {topPlayers&&topPlayers.length>0&&<div className="players-box" style={{position:"relative",overflowY:"auto",maxHeight:"220px",border:isFrozen?"1.5px solid #00f0ff":isDamaged?"1px solid rgba(255,51,51,.5)":isGalaxyBenefited?"1px solid #7dd3fc":isDonutActive?"1px solid rgba(255,105,180,.5)":isCowboyActive?"1.5px solid #ff6622":genderTheme?`1px solid ${genderTheme.border}`:"1px solid rgba(125,211,252,.5)",background:isFrozen?"linear-gradient(145deg,rgba(0,150,200,.4),rgba(0,60,120,.6))":isDamaged?"linear-gradient(145deg,rgba(50,15,15,.92),rgba(20,5,5,.96))":isGalaxyBenefited?"linear-gradient(145deg,rgba(0,30,90,.9),rgba(50,0,140,.9))":isDonutActive?"linear-gradient(145deg,rgba(160,30,90,.85),rgba(90,10,50,.85))":isCowboyActive?"linear-gradient(145deg,rgba(100,40,15,.96),rgba(50,20,10,.96))":genderTheme?"linear-gradient(145deg,rgba(255,255,255,.92),rgba(235,240,248,.92))":"linear-gradient(145deg,rgba(232,238,244,.98),rgba(207,216,226,.98))",boxShadow:"0 3px 12px rgba(0,0,0,.5),inset 0 1px 1px rgba(255,255,255,.45)"}}>
      {isFrozen&&<div className="mvp-ice-layer"><div style={{fontSize:"11px",fontWeight:900,color:"#00f0ff",textShadow:"0 0 10px rgba(0,240,255,1)",textTransform:"uppercase",letterSpacing:"1px",whiteSpace:"nowrap"}}>❄️ FROZEN / CONGELADO ❄️</div></div>}
      {isGalaxyBenefited&&galaxyPopup?<div style={{padding:"4px 2px",textAlign:"center",display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",height:"100%"}}><div style={{fontSize:"11.5px",fontWeight:900,color:"#fff",textShadow:"0 0 8px rgba(125,211,252,.8)",textTransform:"uppercase",letterSpacing:".8px"}}>✨ {galaxyPopup.sender} ✨</div><div style={{fontSize:"7.5px",fontWeight:900,color:"#fff",background:"rgba(0,0,0,.85)",padding:"1.5px 5px",borderRadius:"3px",textTransform:"uppercase",display:"inline-block",boxShadow:"0 0 6px rgba(255,255,255,.35)",letterSpacing:".5px",marginTop:"3px"}}>GALAXY • +1 RONDA</div></div>:<><div className="players-title" style={{color:genderTheme?(isGirlsTeam?"#7a174f":"#08345f"):"#102a43",position:"relative",zIndex:2,textShadow:"none"}}>{isFrozen?"❄️ MVP CONGELADOS":isDamaged?"💥 BAJO FUEGO":isDonutActive?"🍩 EL MUDO • RETO":isCowboyActive?"🤠 RETO CREATIVO":(roundMvpTitle||"🏆 MVPS (TOP 10)")}</div>{topPlayers.map((player,index)=>{const rawPoints=player.points||0;const displayPoints=rawPoints>0?rawPoints:(player.wins||0);const hasRankUp=rankDeltas[player.id]!==undefined;const deltaVal=rankDeltas[player.id];const isWinMvp=String(player.id)===String(winMvpId)||String(player.playerId)===String(winMvpId);const isGiftMvp=String(player.id)===String(giftMvpId)||String(player.playerId)===String(giftMvpId);const mvpRounds=getPlayerMvpRounds(player.id||player.playerId);const contributionPoints=getPlayerContributionPoints(player.id||player.playerId);return <div key={player.id} className={`gamer-player ${hasRankUp?"rank-up-highlight":""}`} style={{position:"relative",zIndex:2,background:hasRankUp?"linear-gradient(135deg,rgba(57,255,136,.28),rgba(255,255,255,.45))":"rgba(255,255,255,.58)",transition:"all .5s ease"}}><div className="player-position">{index===0?"🥇":index===1?"🥈":index===2?"🥉":`${index+1}º`} <span className="player-name" style={{color:"#102a43",fontWeight:900,textShadow:"none"}}>{player.name}</span>{mvpRounds>0&&<span style={{marginLeft:"4px",fontSize:"8px",fontWeight:950,color:genderTheme?(isGirlsTeam?"#a21caf":"#075985"):"#7c3aed"}}>🏆 {mvpRounds}</span>}{contributionPoints>0&&<span style={{marginLeft:"4px",fontSize:"7px",fontWeight:950,color:"#b45309"}}>💠 +{contributionPoints} APORTE</span>}{isWinMvp&&<span style={{marginLeft:"4px",fontSize:"8px",fontWeight:950,color:"#15803d"}}>👑 WIN</span>}{isGiftMvp&&<span style={{marginLeft:"4px",fontSize:"8px",fontWeight:950,color:"#a16207"}}>🎁 MVP</span>}{hasRankUp&&<span className="rank-delta-badge" style={{marginLeft:"4px"}}>▲ +{deltaVal}</span>}</div><div className="player-points" style={{color:"#102a43",fontWeight:950,textShadow:"none"}}>{displayPoints} pts</div></div>})}</>}
    </div>}
  </div>;
}
